import { AgentInfo } from "@/types";

export const agents: AgentInfo[] = [
  {
    name: "zeus",
    displayName: "Zeus",
    domain: "Orchestrator",
    description: "Receives commands and delegates to the right agent",
    color: "#f59e0b",
    icon: "zap",
  },
  {
    name: "hermes",
    displayName: "Hermes",
    domain: "Communications",
    description: "Email, Slack, and Discord management",
    color: "#14b8a6",
    icon: "send",
  },
  {
    name: "athena",
    displayName: "Athena",
    domain: "Code & Dev",
    description: "GitHub, PRs, code generation, deployments",
    color: "#8b5cf6",
    icon: "code",
  },
  {
    name: "apollo",
    displayName: "Apollo",
    domain: "Calendar",
    description: "Scheduling, events, and daily briefings",
    color: "#f97316",
    icon: "calendar",
  },
  {
    name: "artemis",
    displayName: "Artemis",
    domain: "Tasks & Productivity",
    description: "Todos, habits, goals, and focus sessions",
    color: "#10b981",
    icon: "target",
  },
  {
    name: "ares",
    displayName: "Ares",
    domain: "System & DevOps",
    description: "Monitoring, deployments, and error analysis",
    color: "#ef4444",
    icon: "shield",
  },
  {
    name: "hera",
    displayName: "Hera",
    domain: "Memory & Knowledge",
    description: "Notes, bookmarks, and semantic search",
    color: "#d946ef",
    icon: "brain",
  },
  {
    name: "meridian",
    displayName: "Meridian",
    domain: "Geopolitical Intelligence",
    description: "Globe control, news briefings, conflict analysis",
    color: "#00d4ff",
    icon: "globe",
  },
  {
    name: "chicago",
    displayName: "Chicago",
    domain: "City Intelligence",
    description: "Transit, weather, events, food, sports",
    color: "#3b82f6",
    icon: "map-pin",
  },
  {
    name: "flexport",
    displayName: "Flexport",
    domain: "Sales Intelligence",
    description: "Prospects, pipeline, trade signals, vessels",
    color: "#f59e0b",
    icon: "trending-up",
  },
  {
    name: "clio",
    displayName: "Clio",
    domain: "Voice Notes",
    description: "Record, transcribe, and summarize voice notes",
    color: "#a3e635",
    icon: "pen",
  },
  {
    name: "poseidon",
    displayName: "Poseidon",
    domain: "Web Intelligence",
    description: "Web scraping, research, link analysis, and deep search",
    color: "#38bdf8",
    icon: "search",
  },
  {
    name: "iris",
    displayName: "Iris",
    domain: "Screen & Vision",
    description: "Screenshot analysis, OCR, visual understanding, and screen context",
    color: "#fb7185",
    icon: "eye",
  },
];

export function getAgent(name: string): AgentInfo | undefined {
  return agents.find((a) => a.name === name);
}
